### ISSUE TITLE
[건의] inteface github페이지 repository 말고 organization 으로 관리하는 방안

### ISSUE THREAD

**Issue by riyenas0925** [sejong-interface/github-test#10]
@jkey20 @soobin99 @ghk71 interface github페이지에 대해서repository말고 organization으로 관리하는거에 대해서 어떻게 생각하십니까 고문님 ^^ 팀으로 관리하기도 편하고 권한 부여도 편할것 같은데 예전에 만들어둔 sejong interface organization로 다음 집부 부터 사용하는거 어떠십니까 [interface organization 바로가기](https://github.com/sejonginterface) 32기 학술 태그 부탁합니다

**Comment by dev210202** [comment]
내 생각엔 인페 organization은 인페사람들 가이드용 문서들이 있어서 놔두는게 나을거같고
솔직히 학술적인거 많이하려면 애들이 알아서 잘 하겠지... 군생활에 신경쓰라구 동민..!

**Comment by riyenas0925** [comment]
@jkey20 군생활은 뭐 신경쓸것도 없고 ㅋㅋ
뭐 학술적인 부분은 애들이 알아서 하는게 당연한거고 기존에 불편한건 고치는게 좋을것 같아서 지금 보면 인터페이스 repository에 매번 프로젝트 할때마다 새로 organization 만들어서 너무 혼잡하지 않나? ""a  이럴꺼면 한 조직에 전부 정리하는게 좋을것 같아서 말해봤음

→ 2017년도 프로그래밍 전시회([https://github.com/Interface518](https://github.com/Interface518))  
→ 2018년도 프로그래밍 전시회([https://github.com/2018-Interface-Programming-Exhibition](https://github.com/2018-Interface-Programming-Exhibition))  
→ 2019 안드로이드 어플(https://github.com/2019androidtp)

**Comment by dev210202** [comment]
아예 통합으로 하나 할게 필요하긴 할거같다 프로젝트용 하나 만들어야할듯? 다음 고문에게 전달하도록하겠음!!
잘 지내고 있는거 같아서 다행이구만 ^^ 휴가나오면 연락하고~

**Comment by nhk9680** [comment]
@riyenas0925 @jkey20 어차피 마이그레이션은 편하게 왔다갔다 가능하니까 우선은 한군데에 리포들 몰아놓고 정리하면될듯?

**Comment by riyenas0925** [comment]
@nhk9680 @jkey20 그래서 팀단위로 관리 하기 편한 [인터페이스 조직](https://github.com/sejonginterface)으로 하는게 좋을것 같은디
